steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'asia-south1-docker.pkg.dev/argus-prism/prism-repo/prism-api:latest', '-f', 'services/api/Dockerfile.cloudrun', '.']
images:
- 'asia-south1-docker.pkg.dev/argus-prism/prism-repo/prism-api:latest'
