"""
FIU-IND XML Generator for ARGUS-PRISM AutoSTR.
Produces regulatory-compliant STR XML packages in FIU-IND v2.0 format.
"""

import hashlib
import logging
import xml.etree.ElementTree as ET
from datetime import datetime, timezone
from typing import List
from xml.dom import minidom
from dateutil import tz

from .schemas.fiu_schema import FIUReportInput, SHAPAttribution

logger = logging.getLogger("prism.autostr.fiu_xml")

# --- PRIVACY FUNCTIONS ---

def hash_aadhaar(raw: str) -> str:
    """SHA-256 hash of raw Aadhaar number."""
    if not raw:
        return ""
    return hashlib.sha256(raw.strip().encode()).hexdigest()

def hash_pan(raw: str) -> str:
    """SHA-256 hash of raw PAN number."""
    if not raw:
        return ""
    return hashlib.sha256(raw.strip().upper().encode()).hexdigest()

def mask_mobile(number: str) -> str:
    """Masks mobile number, showing only last 4 digits."""
    if not number or len(number) < 4:
        return "XXXXXX"
    return "XXXXXX" + number[-4:]

def hash_device_id(imei: str) -> str:
    """SHA-256 hash of raw device IMEI."""
    if not imei:
        return ""
    return hashlib.sha256(imei.strip().encode()).hexdigest()

def mask_ip(ip: str) -> str:
    """Masks IP address, showing only first two octets."""
    if not ip:
        return "x.x.x.x"
    parts = ip.split(".")
    if len(parts) != 4:
        return "x.x.x.x"
    return f"{parts[0]}.{parts[1]}.x.x"

# --- HELPER FUNCTIONS ---

def format_datetime_ist(dt: datetime) -> str:
    """Formats datetime to ISO 8601 with IST offset (+05:30)."""
    ist = tz.gettz("Asia/Kolkata")
    if dt.tzinfo is None:
        dt = dt.replace(tzinfo=timezone.utc)
    dt_ist = dt.astimezone(ist)
    return dt_ist.strftime("%Y-%m-%dT%H:%M:%S+05:30")

def format_amount(amount: float) -> str:
    """Formats float to 2 decimal places."""
    return f"{amount:.2f}"

def generate_suspicion_narrative(
    shap: SHAPAttribution, 
    warmth_score: float,
    account_id: str,
    detection_timestamp: datetime
) -> str:
    """
    Auto-generates the suspicion narrative from SHAP attribution.
    """
    ts_str = format_datetime_ist(detection_timestamp)
    return (
        f"Account {account_id} flagged under PMLA Section 12 "
        f"reporting obligation. WarmthScore: {warmth_score:.1f}/100 "
        f"exceeding mandatory threshold of 75.0. \n\n"
        f"Primary behavioural indicator: {shap.primary_signal} "
        f"(SHAP contribution: {shap.primary_impact:.2f} points). \n"
        f"Secondary indicator: {shap.secondary_signal} "
        f"(SHAP contribution: {shap.secondary_impact:.2f} points). \n"
        f"Tertiary indicator: {shap.tertiary_signal} "
        f"(SHAP contribution: {shap.tertiary_impact:.2f} points).\n\n"
        f"Detection timestamp: {ts_str}. \n"
        f"Automated STR generated by ARGUS-PRISM AutoSTR Engine v2 "
        f"under RBI Cyber Security Framework mandate for real-time "
        f"transaction monitoring. Filing entity: Union Bank of India."
    )

def compute_document_hash(xml_string: str) -> str:
    """Computes SHA-256 hash of the final XML string for integrity."""
    return hashlib.sha256(xml_string.encode()).hexdigest()

def prettify(elem: ET.Element) -> str:
    """Returns a pretty-printed XML string for the Element."""
    rough_string = ET.tostring(elem, 'utf-8')
    reparsed = minidom.parseString(rough_string)
    return reparsed.toprettyxml(indent="  ")

# --- MAIN GENERATOR ---

def generate_fiu_xml(report_input: FIUReportInput) -> str:
    """
    Main entry point for generating the FIU-IND STR XML.
    """
    root = ET.Element("FIUReport")
    root.set("version", "2.0")
    root.set("xmlns", "http://fiuindia.gov.in/str/v2")
    
    # SECTION 1 — SAPTRN
    saptrn = ET.SubElement(root, "SAPTRN")
    ET.SubElement(saptrn, "ReportingEntityName").text = "UNION BANK OF INDIA"
    ET.SubElement(saptrn, "ReportingEntityCode").text = report_input.reporting_entity_code
    ET.SubElement(saptrn, "ReportDate").text = format_datetime_ist(datetime.now(timezone.utc))
    ET.SubElement(saptrn, "ReportType").text = "STR"
    ET.SubElement(saptrn, "PrincipalOfficerName").text = report_input.principal_officer_name
    ET.SubElement(saptrn, "PrincipalOfficerDesignation").text = report_input.principal_officer_designation
    ET.SubElement(saptrn, "PrincipalOfficerEmail").text = report_input.principal_officer_email

    # SECTION 2 — SAPINP
    sapinp = ET.SubElement(root, "SAPINP")
    for acc in report_input.accounts:
        person = ET.SubElement(sapinp, "Person")
        ET.SubElement(person, "AccountID").text = acc.account_id
        ET.SubElement(person, "AccountType").text = acc.account_type
        ET.SubElement(person, "AccountHolderName").text = acc.holder_name
        ET.SubElement(person, "MobileNumber").text = mask_mobile(acc.mobile_raw)
        ET.SubElement(person, "AadhaarHash").text = hash_aadhaar(acc.aadhaar_raw)
        ET.SubElement(person, "PANHash").text = hash_pan(acc.pan_raw)
        ET.SubElement(person, "BranchCode").text = acc.branch_code
        ET.SubElement(person, "IFSC").text = acc.ifsc
        ET.SubElement(person, "KYCStatus").text = acc.kyc_status
        ET.SubElement(person, "WarmthScore").text = str(acc.warmth_score)
        ET.SubElement(person, "RiskLevel").text = acc.risk_level

    # SECTION 3 — SAPLEP
    saplep = ET.SubElement(root, "SAPLEP")
    # Using first account as primary for narrative
    primary_acc = report_input.accounts[0]
    narrative = generate_suspicion_narrative(
        report_input.shap_attribution,
        report_input.threshold_crossed,
        primary_acc.account_id,
        report_input.detection_timestamp
    )
    ET.SubElement(saplep, "SuspicionGrounds").text = narrative
    ET.SubElement(saplep, "DetectionTimestamp").text = format_datetime_ist(report_input.detection_timestamp)
    ET.SubElement(saplep, "ThresholdCrossed").text = str(report_input.threshold_crossed)
    ET.SubElement(saplep, "LegalBasis").text = "PMLA Section 12 — Mandatory STR Filing"
    
    evidence = ET.SubElement(saplep, "SignalEvidence")
    for sig in report_input.signal_scores:
        sig_elem = ET.SubElement(evidence, "Signal")
        ET.SubElement(sig_elem, "SignalName").text = sig.signal_name
        ET.SubElement(sig_elem, "RawScore").text = str(sig.raw_score)
        ET.SubElement(sig_elem, "WeightedScore").text = str(sig.weighted_score)
        ET.SubElement(sig_elem, "ShapImpact").text = str(sig.shap_impact)

    # SECTION 4 — SAPPIT
    sappit = ET.SubElement(root, "SAPPIT")
    for txn in report_input.transactions:
        tx_elem = ET.SubElement(sappit, "Transaction")
        ET.SubElement(tx_elem, "TransactionID").text = txn.transaction_id
        ET.SubElement(tx_elem, "TransactionType").text = txn.transaction_type
        ET.SubElement(tx_elem, "Amount").text = format_amount(txn.amount)
        ET.SubElement(tx_elem, "Currency").text = "INR"
        ET.SubElement(tx_elem, "TransactionTimestamp").text = format_datetime_ist(txn.transaction_timestamp)
        ET.SubElement(tx_elem, "SourceAccountID").text = txn.source_account_id
        ET.SubElement(tx_elem, "DestinationAccountID").text = txn.destination_account_id
        ET.SubElement(tx_elem, "Channel").text = txn.channel
        ET.SubElement(tx_elem, "DeviceID").text = hash_device_id(txn.device_id_raw)
        ET.SubElement(tx_elem, "IPAddress").text = mask_ip(txn.ip_address_raw)

    # Finalize XML
    generated_at = format_datetime_ist(datetime.now(timezone.utc))
    root.set("generated_at", generated_at)
    
    # Prettify and Compute Hash
    xml_str = prettify(root)
    # Note: Pretty printing adds whitespace which we include in the hash for integrity
    doc_hash = compute_document_hash(xml_str)
    
    # Add hash as attribute (we have to regenerate or inject it)
    # To keep it clean, we'll re-parse or just use string manipulation for the root attribute
    # Actually, it's better to add the attribute BEFORE prettifying, 
    # but the hash must be on the FINAL string.
    # FIU-IND specs usually want the hash of the CONTENT.
    # For PRISM, we will hash the XML string WITHOUT the doc_hash attribute first, 
    # then inject the attribute.
    
    root.set("doc_hash", doc_hash)
    final_xml = prettify(root)
    
    return final_xml

if __name__ == "__main__":
    from .schemas.fiu_schema import AccountRecord, TransactionRecord, SignalScore, SHAPAttribution
    
    # Minimal Demo
    demo_input = FIUReportInput(
        case_id="UBI-2026-DEMO-001",
        reporting_entity_code="UBI0001",
        principal_officer_name="Pranav Panchal",
        principal_officer_designation="Chief Compliance Officer",
        principal_officer_email="compliance@unionbankofindia.co.in",
        detection_timestamp=datetime.now(timezone.utc),
        threshold_crossed=82.5,
        accounts=[
            AccountRecord(
                account_id="ACC-7842",
                account_type="SAVINGS",
                holder_name="John Doe",
                mobile_raw="+919876543210",
                aadhaar_raw="123456789012",
                pan_raw="ABCDE1234F",
                branch_code="UBI-MUM-01",
                ifsc="UBIN0550001",
                kyc_status="VERIFIED",
                warmth_score=82.5,
                risk_level="CRITICAL"
            )
        ],
        transactions=[
            TransactionRecord(
                transaction_id="TXN-999",
                transaction_type="UPI",
                amount=50000.0,
                transaction_timestamp=datetime.now(timezone.utc),
                source_account_id="ACC-EXT-1",
                destination_account_id="ACC-7842",
                channel="GPay",
                device_id_raw="IMEI-555-444",
                ip_address_raw="192.168.1.50"
            )
        ],
        signal_scores=[
            SignalScore(signal_name="test_credit_pattern", raw_score=0.9, weighted_score=16.2, shap_impact=1.2),
            SignalScore(signal_name="device_fingerprint", raw_score=0.8, weighted_score=17.6, shap_impact=0.9),
            SignalScore(signal_name="velocity_derivative", raw_score=0.7, weighted_score=10.5, shap_impact=0.5),
            SignalScore(signal_name="dormant_reactivation", raw_score=0.1, weighted_score=2.0, shap_impact=-0.1),
            SignalScore(signal_name="fri_contradiction", raw_score=0.2, weighted_score=3.0, shap_impact=0.1),
            SignalScore(signal_name="sim_swap_velocity", raw_score=0.0, weighted_score=0.0, shap_impact=0.0),
        ],
        shap_attribution=SHAPAttribution(
            primary_signal="test_credit_pattern", primary_impact=1.2,
            secondary_signal="device_fingerprint", secondary_impact=0.9,
            tertiary_signal="velocity_derivative", tertiary_impact=0.5
        )
    )
    
    xml_output = generate_fiu_xml(demo_input)
    print(xml_output)
