steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'asia-south1-docker.pkg.dev/argus-prism/prism-repo/prism-simulator:latest', '-f', 'services/simulator/Dockerfile', '.']
images:
- 'asia-south1-docker.pkg.dev/argus-prism/prism-repo/prism-simulator:latest'
