steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'asia-south1-docker.pkg.dev/argus-prism/prism-repo/prism-pipeline:latest', '-f', 'services/pipeline/Dockerfile', '.']
images:
- 'asia-south1-docker.pkg.dev/argus-prism/prism-repo/prism-pipeline:latest'
