import React from 'react';

const CBIPackageViewer = ({ data }) => {
  if (!data) return null;

  const formatCurrency = (val) => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(val);

  return (
    <div className="cbi-document">
      <header className="cbi-header" style={{ position: 'relative' }}>
        <div style={{ position: 'absolute', right: 0, top: 0, border: '1px solid var(--phosphor)', padding: '8px 16px', color: 'var(--phosphor)', fontFamily: 'var(--font-ui)', fontSize: '8px', letterSpacing: '0.2em' }}>
          PRISM VERIFIED
        </div>
        <h1 className="cbi-header__title">CENTRAL BUREAU OF INVESTIGATION</h1>
        <div className="font-ui ghost-text" style={{ fontSize: '10px', letterSpacing: '0.1em' }}>DIGITAL ARREST FRAUD — EVIDENCE PACKAGE</div>
        <div className="font-data phosphor-text" style={{ fontSize: '10px', marginTop: '8px', display: 'flex', justifyContent: 'space-between' }}>
          <span>SC WRIT 03/2025 · CASE: {data.case_reference}</span>
          <span style={{ opacity: 0.5 }}>AUTO-GENERATED VIA PRISM-AUTOSTR-V2</span>
        </div>
      </header>

      <div className="cbi-metadata">
        <div className="cbi-meta-cell">
          <div className="font-ui ghost-text" style={{ fontSize: '8px' }}>PREPARED AT</div>
          <div className="font-data" style={{ fontSize: '11px' }}>{data.prepared_at}</div>
        </div>
        <div className="cbi-meta-cell">
          <div className="font-ui ghost-text" style={{ fontSize: '8px' }}>PREPARED FOR</div>
          <div className="font-data" style={{ fontSize: '11px' }}>CBI Cyber Crime Wing</div>
        </div>
        <div className="cbi-meta-cell">
          <div className="font-ui ghost-text" style={{ fontSize: '8px' }}>GENERATED BY</div>
          <div className="font-data" style={{ fontSize: '11px' }}>ARGUS-PRISM AutoSTR v2.0</div>
        </div>
      </div>

      <section className="cbi-section">
        <div className="cbi-section__header">01 · EXECUTIVE SUMMARY</div>
        <p className="font-data" style={{ fontSize: '11px', lineHeight: '1.8', color: 'var(--instrument-white)' }}>
          {data.executive_summary}
        </p>
      </section>

      <section className="cbi-section">
        <div className="cbi-section__header">02 · TRANSACTION LINEAGE</div>
        <table className="cbi-table">
          <thead>
            <tr>
              <th>STEP</th>
              <th>DESCRIPTION</th>
              <th>FROM</th>
              <th>TO</th>
              <th>AMOUNT</th>
              <th>CHANNEL</th>
              <th>TIMESTAMP</th>
            </tr>
          </thead>
          <tbody>
            {data.transaction_lineage.map((t, i) => (
              <tr key={i}>
                <td>{t.step}</td>
                <td>{t.description}</td>
                <td>{t.from}</td>
                <td>{t.to}</td>
                <td style={{ color: t.amount > 100000 ? 'var(--phosphor)' : 'var(--instrument-white)' }}>
                  {formatCurrency(t.amount)}
                </td>
                <td>{t.channel}</td>
                <td>{t.timestamp.split('T')[1]}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </section>

      <section className="cbi-section">
        <div className="cbi-section__header">03 · DEVICE TIMELINE</div>
        <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
          {data.device_timeline.map((e, i) => (
            <div key={i} style={{ display: 'flex', gap: '24px', paddingLeft: e.score_impact ? '12px' : '0', borderLeft: e.score_impact ? '4px solid var(--phosphor)' : 'none' }}>
              <div className="font-data ghost-text" style={{ width: '60px', fontSize: '9px' }}>HOUR {e.hour}</div>
              <div style={{ display: 'flex', flexDirection: 'column' }}>
                <div className="font-data" style={{ fontSize: '11px', color: e.score_impact ? 'var(--phosphor)' : 'var(--instrument-white)' }}>{e.event}</div>
                {e.device_id && <div className="font-data ghost-text" style={{ fontSize: '9px' }}>DEVICE: {e.device_id}</div>}
              </div>
            </div>
          ))}
        </div>
      </section>

      <section className="cbi-section">
        <div className="cbi-section__header">04 · LEGAL BASIS FOR RESTRICTION</div>
        <p className="font-data" style={{ fontSize: '11px', lineHeight: '1.6', color: 'var(--instrument-white)' }}>
          RBI KYC Master Direction 2016 <span className="phosphor-text">Section 38</span> — Account restricted at WarmthScore 77 (threshold: 75) without court order. 
          Compliance with <span className="phosphor-text">Section 12</span> of PMLA and Supreme Court <span className="phosphor-text">Writ 03/2025</span>.
        </p>
      </section>

      <section className="cbi-section">
        <div className="cbi-section__header">05 · RECOMMENDED CHARGES</div>
        <div style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}>
          {data.recommended_charges.split('. ').map((charge, i) => (
            <div key={i} style={{ paddingLeft: '12px', borderLeft: '1px solid var(--instrument-white)', fontSize: '11px', fontFamily: 'var(--font-data)' }}>
              {charge}
            </div>
          ))}
        </div>
      </section>

      <button className="action-btn action-btn--primary" style={{ width: '100%', padding: '16px' }}>
        DOWNLOAD CBI PACKAGE — PDF
      </button>
    </div>
  );
};

export default CBIPackageViewer;
