import React, { useState, useEffect } from 'react';
import useNumberScanner from '../../hooks/useNumberScanner';

const RBIReportViewer = ({ data }) => {
  const [showBars, setShowBars] = useState(false);

  useEffect(() => {
    const timer = setTimeout(() => setShowBars(true), 100);
    return () => clearTimeout(timer);
  }, []);

  const formatCurrency = (val) => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(val);

  const stats = data.summary_stats;
  const strScanner = useNumberScanner(stats.total_str_filed, 800);
  const flaggedScanner = useNumberScanner(stats.total_accounts_flagged, 800);
  const frozenScanner = useNumberScanner(stats.total_accounts_frozen, 800);
  const valueScanner = useNumberScanner(stats.total_value_protected, 1200);

  return (
    <div className="rbi-report">
      <header className="cbi-header">
        <h1 className="cbi-header__title">RESERVE BANK OF INDIA</h1>
        <div className="font-ui ghost-text" style={{ fontSize: '10px', letterSpacing: '0.1em' }}>CYBER FRAUD INTELLIGENCE REPORT — {data.report_period}</div>
        <div className="font-data ghost-text" style={{ fontSize: '10px', marginTop: '8px' }}>
          UNION BANK OF INDIA · GENERATED BY PRISM
        </div>
      </header>

      <div className="rbi-stats-grid">
        <div className="rbi-stat-cell">
          <span className="rbi-stat-value">{strScanner.displayValue.toFixed(0)}</span>
          <span className="rbi-stat-label">TOTAL STR FILED</span>
        </div>
        <div className="rbi-stat-cell">
          <span className="rbi-stat-value">{flaggedScanner.displayValue.toFixed(0)}</span>
          <span className="rbi-stat-label">ACCOUNTS FLAGGED</span>
        </div>
        <div className="rbi-stat-cell">
          <span className="rbi-stat-value">{frozenScanner.displayValue.toFixed(0)}</span>
          <span className="rbi-stat-label">ACCOUNTS FROZEN</span>
        </div>
        <div className="rbi-stat-cell">
          <span className="rbi-stat-value" style={{ fontSize: '20px' }}>{formatCurrency(valueScanner.displayValue)}</span>
          <span className="rbi-stat-label">VALUE PROTECTED</span>
        </div>
        <div className="rbi-stat-cell">
          <span className="rbi-stat-value">{stats.false_positive_rate.toFixed(1)}%</span>
          <span className="rbi-stat-label">FALSE POSITIVE</span>
        </div>
        <div className="rbi-stat-cell">
          <span className="rbi-stat-value" style={{ fontSize: '20px' }}>{stats.avg_detection_lead_time_hours}H</span>
          <span className="rbi-stat-label">AVG DETECTION LEAD</span>
        </div>
      </div>

      <section className="cbi-section">
        <div className="cbi-section__header">PATTERN BREAKDOWN</div>
        <div style={{ display: 'flex', flexDirection: 'column', gap: '20px' }}>
          {data.pattern_breakdown.map((p, i) => (
            <div key={i} className="rbi-bar-row">
              <div className="rbi-bar-label">{p.pattern}</div>
              <div className="rbi-bar-track">
                <div 
                  className="rbi-bar-fill" 
                  style={{ width: showBars ? `${(p.count / 8) * 100}%` : '0%' }} 
                />
              </div>
              <div className="rbi-bar-value">{p.count}</div>
            </div>
          ))}
        </div>
      </section>

      <section className="cbi-section">
        <div className="cbi-section__header">SIGNAL ACCURACY</div>
        <table className="cbi-table">
          <thead>
            <tr>
              <th style={{ width: '300px' }}>SIGNAL</th>
              <th>TRIGGERS</th>
              <th>CONFIRMED</th>
              <th>ACCURACY</th>
            </tr>
          </thead>
          <tbody>
            {data.signal_performance.map((s, i) => (
              <tr key={i}>
                <td className="font-data">{s.signal}</td>
                <td>{s.triggers}</td>
                <td>{s.confirmed_mule}</td>
                <td style={{ color: s.accuracy === 100 ? 'var(--phosphor)' : 'var(--instrument-white)' }}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
                    <div className="rbi-bar-track" style={{ width: '100px', maxWidth: '100px' }}>
                      <div 
                        className="rbi-bar-fill" 
                        style={{ width: showBars ? `${s.accuracy}%` : '0%' }} 
                      />
                    </div>
                    {s.accuracy}%
                  </div>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </section>
    </div>
  );
};

export default RBIReportViewer;
